### PR TITLE
Test Release Camera App

### PR DESCRIPTION
**Pull request by sadiul-hakim**
## What type of PR is this? (check all applicable)

- [X ] 🍕 New feature/project
- [ ] 🐛 Bug fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

## Related Issues & Documents

- Related Issue #

### CODE REVIEW

**Comment by Jisan-mia** [comment]
@sadiul-hakim bhaiya, please add me as pr reviewer before merging, by this we can avoid potential bugs and can improve code quality

**Comment by sadiul-hakim** [comment]
Final version released

**Comment by Jisan-mia** [comment]
@sadiul-hakim bhaiya, for every pr you'll raise, add me as pr reviewer before merging

**Comment by sadiul-hakim** [comment]
Ok, will do that.

**Comment by Jisan-mia** [comment]
Thanks, bhaiya, let's expand this project collaboratively

**Comment by sadiul-hakim** [comment]
You can changes the photo of my projects to make them standard

**Comment by Jisan-mia** [comment]
When you'll raise a pr, I'll review it and you can make changes according to the review bhai including photos

**Comment by sadiul-hakim** [comment]
No i am talking about existing ones

**Pull request merged**
